"""
Forecast vs Actual Telemetry Comparison Engine.
Ingests external forecast inputs, compares pre-deployment baseline and post-deployment actual CloudWatch telemetry,
calculates error metrics and range bounds, and produces a normalized comparison report.
Maintains strict non-causal measurement language.
"""

import logging
from datetime import datetime, timezone
from enum import Enum
from typing import Dict, List, Optional, Tuple, Union, Any
from pydantic import BaseModel, Field, ConfigDict

from aws.models.aws_models import ResourceType
from aws.events.event_models import DeploymentSnapshot, DeploymentStatus
from aws.telemetry.metrics import LambdaMetrics, DynamoDBMetrics
from aws.telemetry.telemetry_loop import (
    TelemetryLoopService,
    TelemetryWindow,
    WindowType,
)

logger = logging.getLogger("infrashift.aws.telemetry.comparison")


class ComparisonStatus(str, Enum):
    """Data usability classification for forecast vs actual comparisons."""

    USABLE = "usable"
    NO_ACTUAL_DATA = "no_actual_data"
    NO_FORECAST_DATA = "no_forecast_data"
    INSUFFICIENT_ACTUAL_DATA = "insufficient_actual_data"
    INVALID_FORECAST = "invalid_forecast"


class MetricForecast(BaseModel):
    """
    Externally supplied forecast values for a single AWS metric.
    Ingested from Person 1's forecasting layer. Never generated by AWS layer.
    """

    model_config = ConfigDict(extra="ignore")

    predicted_value: float = Field(description="Predicted metric value")
    lower_bound: Optional[float] = Field(default=None, description="Lower prediction interval bound")
    upper_bound: Optional[float] = Field(default=None, description="Upper prediction interval bound")
    unit: Optional[str] = None


class ResourceForecastInput(BaseModel):
    """
    External forecast container for a specific AWS resource.
    """

    model_config = ConfigDict(extra="ignore")

    resource_id: str
    metric_forecasts: Dict[str, MetricForecast] = Field(
        default_factory=dict,
        description="Dictionary mapping metric_name to MetricForecast (e.g. {'Duration': MetricForecast(...)})",
    )


class ActualObservation(BaseModel):
    """
    Actual CloudWatch metric measurement summary.
    """

    model_config = ConfigDict(extra="ignore")

    metric_name: str
    aggregation: str
    value: Optional[float] = Field(default=None, description="Actual aggregated numeric value. None if no data.")
    unit: Optional[str] = None
    datapoint_count: int = 0
    status: str = Field(default="usable", description="'usable' or 'no_data'")


class MetricComparison(BaseModel):
    """
    Comparison result for a single metric comparing forecast vs actual observation.
    """

    model_config = ConfigDict(extra="ignore")

    metric_name: str
    forecast: Optional[MetricForecast] = None
    actual: Optional[ActualObservation] = None
    baseline_value: Optional[float] = Field(default=None, description="Historical pre-deployment baseline value")
    absolute_error: Optional[float] = Field(default=None, description="|actual - predicted|")
    relative_error: Optional[float] = Field(default=None, description="|actual - predicted| / |predicted|")
    within_forecast_range: Optional[bool] = Field(default=None, description="True if lower_bound <= actual <= upper_bound")
    range_status: Optional[str] = Field(default=None, description="'within_range', 'outside_range', 'no_actual_data', 'no_forecast_data'")
    status: ComparisonStatus
    message: Optional[str] = Field(description="Factual, non-causal summary message")


class ResourceComparisonResult(BaseModel):
    """
    Comparison result container for a single AWS resource.
    """

    model_config = ConfigDict(extra="ignore")

    resource_id: str
    resource_type: ResourceType
    resource_name: str
    baseline_window: Dict[str, Any] = Field(default_factory=dict)
    post_deployment_window: Dict[str, Any] = Field(default_factory=dict)
    comparisons: List[MetricComparison] = Field(default_factory=list)


class DeploymentForecastVsActualResult(BaseModel):
    """
    Complete deployment-level forecast-vs-actual comparison report.
    Handoff artifact returned to Person 1's forecasting/AI layer.
    """

    model_config = ConfigDict(extra="ignore")

    deployment_id: str
    change_id: Optional[str] = None
    environment: str
    telemetry_anchor_timestamp: Optional[str] = None
    resources: List[ResourceComparisonResult] = Field(default_factory=list)
    status: str = Field(default="completed", description="'completed', 'no_actual_data', 'no_deployment_anchor', 'error'")
    generated_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="ISO 8601 UTC timestamp of comparison generation",
    )


class ForecastVsActualService:
    """
    Orchestrator for computing forecast-vs-actual telemetry comparisons.
    """

    def __init__(self, loop_service: Optional[TelemetryLoopService] = None):
        self.loop_service = loop_service or TelemetryLoopService()

    def compare_deployment_telemetry(
        self,
        snapshot: DeploymentSnapshot,
        forecasts: Optional[List[ResourceForecastInput]] = None,
        baseline_window_minutes: int = 60,
        post_window_minutes: int = 60,
        period_seconds: int = 300,
    ) -> DeploymentForecastVsActualResult:
        """
        Compare actual post-deployment CloudWatch telemetry against baseline and optional forecasts for a deployment snapshot.

        :param snapshot: DeploymentSnapshot containing deployment completion anchor and deployed resources.
        :param forecasts: Optional list of ResourceForecastInput provided by Person 1's AI/forecasting layer.
        :param baseline_window_minutes: Pre-deployment baseline window duration in minutes (default 60).
        :param post_window_minutes: Post-deployment observation window duration in minutes (default 60).
        :param period_seconds: CloudWatch metric period in seconds (default 300).
        :return: DeploymentForecastVsActualResult object.
        """
        anchor_ts = snapshot.telemetry_anchor_timestamp or snapshot.completed_at
        if not anchor_ts:
            logger.warning("Deployment '%s' has no completed_at timestamp anchor. Cannot fetch telemetry.", snapshot.deployment_id)
            return DeploymentForecastVsActualResult(
                deployment_id=snapshot.deployment_id,
                change_id=snapshot.change_id,
                environment=snapshot.environment.value,
                telemetry_anchor_timestamp=None,
                resources=[],
                status="no_deployment_anchor",
            )

        forecast_map: Dict[str, ResourceForecastInput] = {}
        if forecasts:
            for f in forecasts:
                forecast_map[f.resource_id] = f

        resource_results: List[ResourceComparisonResult] = []

        for res in snapshot.resources:
            res_name = self._extract_resource_name(res.resource_id)
            target_metrics = self._get_metrics_for_type(res.resource_type)
            namespace = self._get_namespace_for_type(res.resource_type)

            res_forecast = forecast_map.get(res.resource_id)
            metric_comparisons: List[MetricComparison] = []

            base_window_info: Dict[str, Any] = {}
            post_window_info: Dict[str, Any] = {}

            for m_name in target_metrics:
                # 1. Retrieve Pre-deployment Baseline
                base_win = self.loop_service.get_pre_deployment_baseline(
                    resource_id=res.resource_id,
                    resource_type=res.resource_type,
                    resource_name=res_name,
                    metric_name=m_name,
                    namespace=namespace,
                    completed_at=anchor_ts,
                    baseline_window_minutes=baseline_window_minutes,
                    period_seconds=period_seconds,
                )

                # 2. Retrieve Post-deployment Actual Telemetry
                post_win = self.loop_service.get_post_deployment_telemetry(
                    resource_id=res.resource_id,
                    resource_type=res.resource_type,
                    resource_name=res_name,
                    metric_name=m_name,
                    namespace=namespace,
                    completed_at=anchor_ts,
                    post_window_minutes=post_window_minutes,
                    period_seconds=period_seconds,
                )

                base_window_info[m_name] = {"start_time": base_win.start_time, "end_time": base_win.end_time}
                post_window_info[m_name] = {"start_time": post_win.start_time, "end_time": post_win.end_time}

                # 3. Extract Forecast if present
                m_forecast = res_forecast.metric_forecasts.get(m_name) if res_forecast else None

                # 4. Compare Forecast vs Actual
                comp = self.compare_metric(
                    forecast=m_forecast,
                    actual_window=post_win,
                    baseline_window=base_win,
                )
                metric_comparisons.append(comp)

            resource_results.append(
                ResourceComparisonResult(
                    resource_id=res.resource_id,
                    resource_type=res.resource_type,
                    resource_name=res_name,
                    baseline_window=base_window_info,
                    post_deployment_window=post_window_info,
                    comparisons=metric_comparisons,
                )
            )

        overall_status = "completed"
        if not resource_results:
            overall_status = "no_actual_data"

        return DeploymentForecastVsActualResult(
            deployment_id=snapshot.deployment_id,
            change_id=snapshot.change_id,
            environment=snapshot.environment.value,
            telemetry_anchor_timestamp=anchor_ts,
            resources=resource_results,
            status=overall_status,
        )

    def compare_metric(
        self,
        forecast: Optional[MetricForecast],
        actual_window: TelemetryWindow,
        baseline_window: TelemetryWindow,
    ) -> MetricComparison:
        """
        Compare a single metric's actual observation against baseline and forecast values.

        :param forecast: Optional MetricForecast provided by forecasting layer.
        :param actual_window: TelemetryWindow representing post-deployment CloudWatch metrics.
        :param baseline_window: TelemetryWindow representing pre-deployment baseline CloudWatch metrics.
        :return: MetricComparison object with neutral error metrics and range calculations.
        """
        metric_name = actual_window.metric_name
        baseline_val = baseline_window.value

        actual_obs = ActualObservation(
            metric_name=metric_name,
            aggregation=actual_window.aggregation,
            value=actual_window.value,
            unit=actual_window.unit,
            datapoint_count=actual_window.datapoint_count,
            status=actual_window.status,
        )

        # Check Usability Status
        if actual_window.value is None:
            comp_status = ComparisonStatus.NO_ACTUAL_DATA
            msg = f"Metric '{metric_name}' has no CloudWatch datapoints in the post-deployment observation window."
            return MetricComparison(
                metric_name=metric_name,
                forecast=forecast,
                actual=actual_obs,
                baseline_value=baseline_val,
                absolute_error=None,
                relative_error=None,
                within_forecast_range=None,
                range_status="no_actual_data",
                status=comp_status,
                message=msg,
            )

        if not forecast:
            comp_status = ComparisonStatus.NO_FORECAST_DATA
            msg = f"Metric '{metric_name}' post-deployment actual average value was {actual_window.value}{actual_window.unit or ''} (baseline: {baseline_val}). No forecast provided."
            return MetricComparison(
                metric_name=metric_name,
                forecast=None,
                actual=actual_obs,
                baseline_value=baseline_val,
                absolute_error=None,
                relative_error=None,
                within_forecast_range=None,
                range_status="no_forecast_data",
                status=comp_status,
                message=msg,
            )

        # 1. Absolute Error: |actual - predicted|
        actual_val = actual_window.value
        predicted_val = forecast.predicted_value
        abs_err = round(abs(actual_val - predicted_val), 4)

        # 2. Relative Error: |actual - predicted| / |predicted| (Safe division)
        rel_err = None
        if predicted_val != 0:
            rel_err = round(abs(actual_val - predicted_val) / abs(predicted_val), 4)

        # 3. Range Bound Checking
        within_range = None
        range_status = "no_forecast_data"

        if forecast.lower_bound is not None and forecast.upper_bound is not None:
            within_range = (actual_val >= forecast.lower_bound) and (actual_val <= forecast.upper_bound)
            range_status = "within_range" if within_range else "outside_range"

        unit_str = f" {actual_window.unit}" if actual_window.unit else ""
        base_str = f" vs baseline {baseline_val}{unit_str}" if baseline_val is not None else ""
        range_str = f", within forecast range [{forecast.lower_bound}, {forecast.upper_bound}]: {within_range}" if within_range is not None else ""

        # Strictly non-causal factual statement
        msg = f"Metric '{metric_name}' post-deployment {actual_window.aggregation} was {actual_val}{unit_str}{base_str} (predicted: {predicted_val}{range_str})."

        return MetricComparison(
            metric_name=metric_name,
            forecast=forecast,
            actual=actual_obs,
            baseline_value=baseline_val,
            absolute_error=abs_err,
            relative_error=rel_err,
            within_forecast_range=within_range,
            range_status=range_status,
            status=ComparisonStatus.USABLE,
            message=msg,
        )

    def _extract_resource_name(self, resource_id: str) -> str:
        """Extract resource name from ARN or ID."""
        if ":" in resource_id or "/" in resource_id:
            parts = resource_id.replace("/", ":").split(":")
            return parts[-1]
        return resource_id

    def _get_metrics_for_type(self, resource_type: ResourceType) -> List[str]:
        """Get standard CloudWatch metric names for resource type."""
        if resource_type == ResourceType.LAMBDA:
            return LambdaMetrics.ALL_DEFAULT
        elif resource_type == ResourceType.DYNAMODB:
            return DynamoDBMetrics.ALL_DEFAULT
        elif resource_type == ResourceType.API_GATEWAY:
            return ["Count", "Latency", "4XXError", "5XXError"]
        return ["Invocations"]

    def _get_namespace_for_type(self, resource_type: ResourceType) -> str:
        """Get CloudWatch namespace for resource type."""
        if resource_type == ResourceType.LAMBDA:
            return "AWS/Lambda"
        elif resource_type == ResourceType.DYNAMODB:
            return "AWS/DynamoDB"
        elif resource_type == ResourceType.API_GATEWAY:
            return "AWS/ApiGateway"
        return "AWS/Custom"
